<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?> 
<configuration>
   <property>
     <name>test.randomwrite..maps_per_host</name>
     <value>3</value>
   </property>
   <property>
     <name>test.randomwrite.min_key</name>
     <value>3</value>
   </property>
   <property>
     <name>test.randomwrite.max_key</name>
     <value>3</value>
   </property>
   <property>
     <name>test.randomwrite.min_value</name>
     <value>90</value>
   </property>
   <property>
     <name>test.randomwrite.max_value</name>
     <value>90</value>
   </property>
   <property>
     <name>test.randomwrite.total_bytes</name>
     <value>573035000</value>
   </property>
   <property>
     <name>test.randomwrite.bytes_per_map</name>
     <value>57303500</value>
   </property>
</configuration>
